<a href="https://colab.research.google.com/github/BDhivya-md3/day_11/blob/main/day_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**k fold cross validation**

In [1]:
#import libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataset = pd.read_csv("/content/Data.csv")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)

[[1000025       5       1 ...       3       1       1]
 [1002945       5       4 ...       3       2       1]
 [1015425       3       1 ...       3       1       1]
 ...
 [ 888820       5      10 ...       8      10       2]
 [ 897471       4       8 ...      10       6       1]
 [ 897471       4       8 ...      10       4       1]]
[2 2 2 2 2 4 2 2 2 2 2 2 4 2 4 4 2 2 4 2 4 4 2 2 4 2 2 2 2 2 2 4 2 2 2 4 2
 4 4 4 4 4 4 2 4 2 2 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 2 4 2 4 4 2 2 4 2 4 4 2
 2 2 2 2 2 2 2 2 4 4 4 4 2 2 2 2 2 2 2 2 2 2 4 4 4 4 2 4 4 4 4 4 2 4 2 4 4
 4 2 2 2 4 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 4 2 2 4 2 4
 4 2 2 4 2 2 4 4 2 2 2 2 4 4 2 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 4 2 4 4 4 2 4
 4 2 2 2 2 2 2 2 2 4 4 2 2 2 4 4 2 2 2 4 4 2 4 4 4 2 2 4 2 2 4 4 4 4 2 4 4
 2 4 4 4 2 4 2 4 4 4 4 2 2 2 2 2 2 4 4 2 2 4 2 4 4 4 2 2 2 2 4 4 4 4 4 2 4
 4 4 2 4 2 4 4 2 2 2 2 4 2 2 4 4 4 4 4 2 4 4 2 2 4 4 2 2 4 4 2 4 2 4 4 2 2
 4 2 2 2 4 2 2 4 4 2 2 4 2 4 2 2 4 2 4 4 4 2 2 4 4 2 4 2 2 4 4 2

In [3]:
#splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.25)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

[[1017122       8      10 ...       9       7       1]
 [ 492561       4       3 ...       2       1       1]
 [ 785615       8       6 ...       3       4       2]
 ...
 [1131411       1       1 ...       2       1       1]
 [1084139       6       3 ...       4       1       1]
 [ 672113       7       5 ...       5       3       1]]
[4 2 4 4 4 2 2 4 4 2 4 2 2 4 2 2 2 2 2 4 2 2 4 2 2 2 4 4 2 2 2 2 2 4 2 4 2
 4 4 4 2 2 2 2 2 2 2 4 2 2 4 2 4 4 2 2 4 2 4 4 2 4 2 2 4 2 4 4 4 2 2 2 2 4
 4 2 2 2 4 2 4 4 4 2 2 2 2 2 2 2 2 2 2 2 4 4 4 2 4 2 4 2 4 2 2 4 2 2 2 2 2
 2 2 2 2 2 2 4 2 2 2 4 2 2 4 2 2 2 2 2 2 2 2 2 2 2 4 2 2 4 2 4 4 2 2 2 2 2
 4 2 4 2 2 4 2 4 2 2 2 2 2 2 2 2 4 2 4 2 2 4 2 2 2 2 2 2 4 2 2 2 4 2 4 2 2
 2 4 2 4 4 4 2 2 2 2 4 2 4 2 2 2 2 2 4 2 4 4 4 2 4 2 2 4 2 4 2 4 4 2 2 4 2
 2 2 2 4 4 4 2 2 4 4 2 4 2 4 2 2 2 2 2 2 2 4 2 2 2 4 4 2 2 4 4 4 2 4 4 4 4
 2 2 2 2 4 2 2 2 4 2 2 2 4 4 2 2 2 4 2 2 2 2 2 2 4 2 2 2 2 2 2 2 4 2 2 4 4
 4 2 2 2 4 4 2 2 4 2 4 2 2 4 2 2 4 4 2 2 2 2 2 2 2 2 2 2 2 2 2 2

In [4]:
#train the xgboost model
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
#pip install xgboost

In [6]:
#confusion matrix and accuracy score
from sklearn.metrics import accuracy_score,confusion_matrix
cm = confusion_matrix(y_pred,y_test)
print(cm)
accuracy_score(y_test,y_pred)

NameError: ignored

In [10]:
#implement k-fold cross validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = xgb,X =x_train,y = y_train,cv =40)
print("accuracy : {:.2f}%".format(accuracies.mean()*100))
print("standard deviation :{:.2f}%".format(accuracies.std()*100))

accuracy : 96.88%
standard deviation :3.83%
